#!/bin/bash
#PBS -l nodes=1:ppn=16:dc2,walltime=0:45:00
#PBS -N app-generatetractmasks
#PBS -V

cd $PBS_O_WORKDIR

module load matlab

export MATLABPATH=$MATLABPATH:$SERVICE_DIR #needed sto find main.m which is installed in $SERVICE_DIR
matlab -nodisplay -nosplash -r main

#matlal doesn't set return code,so we need to check the output file to see if script completed successfully
if [ -d "masks" ];
then 
  echo 0 > finished
else
  echo "directory missing"
  echo 1 > finished
  exit 1
fi
